In [ ]:
import pandas as pd

data = [[1, 8], [2, 8], [3, 8], [4, 7], [5, 9], [6, 9]]
employee = pd.DataFrame(data, columns=['employee_id', 'team_id']).astype({'employee_id':'Int64', 'team_id':'Int64'})

emp_group_by = employee.groupby('team_id').agg({'employee_id': 'count'}).reset_index().rename(columns={'employee_id': 'team_size'})
joined = employee.merge(emp_group_by, on='team_id', how='left')[['employee_id', 'team_size']]

joined

   employee_id  team_size
0            1          3
1            2          3
2            3          3
3            4          1
4            5          2
5            6          2

In [16]:
data = [['Leetcode FC'], ['Ahly SC'], ['Real Madrid']]
teams = pd.DataFrame(data, columns=['team_name']).astype({'team_name':'object'})

joined_df = teams.merge(teams,  how='cross').rename(columns={'team_name_x': 'home_team', 'team_name_y': 'away_team'})
joined_df = joined_df[joined_df['home_team'] != joined_df['away_team']]
joined_df

     home_team    away_team
1  Leetcode FC      Ahly SC
2  Leetcode FC  Real Madrid
3      Ahly SC  Leetcode FC
5      Ahly SC  Real Madrid
6  Real Madrid  Leetcode FC
7  Real Madrid      Ahly SC